### ISSUE TITLE
Cannot load ag-grid with rollup

### ISSUE THREAD

**Issue by robianmcd** [ag-grid/ag-grid-angular#112] opened 2017-01-05 17:15 UTC
I'm getting the error `'AgGridModule' is not exported by node_modules\ag-grid-ng2\main.js` When I try to build an app with rollup that uses ag-grid-ng2. 

rollup.config.js
```js
let commonjs = require('rollup-plugin-commonjs');
let nodeResolve = require('rollup-plugin-node-resolve');

export default {
    entry: 'main.js',
    dest: 'bundle.js',
    format: 'iife',
    plugins: [
        nodeResolve({jsnext: true, module: true}),
        commonjs({include: ['node_modules/rxjs/**', 'node_modules/ag-grid-ng2/**']})
    ]
};
```

main.js
```js
import {AgGridModule} from 'ag-grid-ng2/main';

console.log('imported ag grid', AgGridModule);
```

package.json
```
{
  "name": "ag-grid-app",
  "dependencies": {
    "@angular/compiler": "^2.4.1",
    "@angular/compiler-cli": "^2.4.1",
    "@angular/core": "^2.4.1",
    "ag-grid": "^7.1.0",
    "ag-grid-ng2": "^7.1.2",
    "core-js": "^2.4.1",
    "rollup": "^0.40.0",
    "rollup-plugin-commonjs": "^7.0.0",
    "rollup-plugin-node-resolve": "^2.0.0",
    "rxjs": "^5.0.2",
    "typescript": "^2.1.4",
    "zone.js": "^0.7.4"
  }
}
```

Here is a minimal app that reproduces the issue
[ag-grid-app.zip](https://github.com/ceolter/ag-grid-ng2/files/687853/ag-grid-app.zip)
to get the error message run
```sh
npm install
node_modules/.bin/rollup -c
```

Any idea what could be causing this?

**Comment by seanlandsman** [comment] 2017-01-05 17:29
Try this in your rollup config:

````
commonjs({
    include: ['node_modules/rxjs/**', 'node_modules/ag-grid-ng2/**'],
    namedExports: {
        'node_modules/ag-grid-ng2/main.js': ['AgGridModule']
    }
})
````

**Comment by robianmcd** [comment] 2017-01-05 17:47
Thanks! That fixed the error I was getting from the compiler. Although now I get a runtime error: `Uncaught ReferenceError: require is not defined`

It's coming from this in the bundle

```
////////// MAKE SURE YOU EDIT main-webpack.js IF EDITING THIS FILE!!!

var populateClientExports = require('./dist/lib/clientExports').populateClientExports;
populateClientExports(exports);
```

**Comment by seanlandsman** [comment] 2017-01-09 10:14
Hi

Supporting rollup is something I'd like to look at, but other priorities mean I probably won't get to it anytime soon.

I'll get back to this as soon as I can

**Comment by robianmcd** [comment] 2017-01-09 16:05
Alright thanks for the heads up. Do you think this could be an issue with rollup? If so I'll create an issue on their end too. From my understanding the `rollup-plugin-commonjs` should be converting any `require` statements to ES6 imports and it doesn't seem to be doing that.

By the way if you do find the time to add rollup support it would be great if you could expose the ES6 modules so users don't have to use the `rollup-plugin-commonjs` plugin. details here https://github.com/rollup/rollup/wiki/pkg.module

**Comment by seanlandsman** [comment] 2017-01-10 17:25
hi - honestly I dont know if this is a problem with rollup, rollup-plugin-commonjs or how ag-grid does its exports, so I'm afraid I cant answer that

With regards to moving (or at least offering a version that does) es6 - this is on my list of things I want to do this quarter if I can

**Comment by pdavin** [comment] 2017-01-12 17:23
I also have this problem (rollup config fix worked, but runtime error in ag-grid/main.js). If we can't work around this we may have to not use ag-grid-ng2 and/or ag-grid itself. 
Can I use ag-grid in Angular 2 without ag-grid-ng2? Would it just mean I wouldn't get all the nice component integration?

**Comment by seanlandsman** [comment] 2017-01-12 18:20
You can still use ag-grid without this - as you say you wont be able to integrate components into the grid itself, but that aside it'll work fine.

ag-grid itself is framework agnostic - if you interact with it via javascript it'll work just fine

**Comment by pdavin** [comment] 2017-01-12 18:23
I think this is because ag-grid-ng2 is not bundled. (it has no bundle files, like core angular dependencies do and 3rd party libraries like ng2-charts do)
My understanding of AoT for 3rd party libraries is that bundling is a requirement. Ie, bundling is inherently part of AoT - no one would run an unbundled distributable app. Indeed it's often 50% of the work in getting AoT working. 

So I think this bug is not Rollup specific?  Wouldn't most bundled AoT apps need bundled ag-grid-ng2 code? It's also making it harder to get Karma tests working (ag-grid-ng2/main is trying to load all its dependent components in individually - it'd be easier if I could just include a bundle).

**Comment by seanlandsman** [comment] 2017-01-12 18:25
You can bundle ag-grid-ng2 yourself - look at the ng2 example repo for examples of this

**Comment by pdavin** [comment] 2017-01-12 18:35
Do you mean that ag-grid-ng2-example is bundling ag-grid-ng2 because the example app bundles itself, and therefore it transitively bundles ag-grid-ng2?  That is true, but libraries are typically *distributed* with their bundle. It greatly simplifies the integration process, because shifting the bundling task to the client app means we need to work through any strange errors that emerge in the bundling process, sometimes including ones inside the library's code.

**Comment by jskrzypek** [comment] 2017-02-14 23:22
@pdavin fwiw the problem with bundling is that it can make treeshaking with rollup much harder. Regardless aot doesn't require 3rd party angular code to be bundled, just to provide aot metadata.

**Comment by seanlandsman** [comment] 2017-03-08 16:51
Hi all - I've been taking a look at rollup and have hit a number of issues with it.

Its still a work in progress but at this stage I don't see us being able to offer support for it in the short term I'm afraid.

I have managed to use SystemJS Builder to work, but the resulting bundle wasn't all that much smaller

Sorry I don't have better news for you on this front

**Comment by chcoust** [comment] 2017-03-20 10:15
Hello Sean, 

We are also looking for bundling our application with rollup.

I understand you won't offer support for it short term, what kind of planning could you provide ?

We will try SystemJS for now, but looking forward to hearing from you with rollup

Charles

**Comment by chcoust** [comment] 2017-03-28 16:18
Hello, 

Yes we managed to minify and bundle our app with webpack (and even got rid of SystemJS)

Charles

**Comment by seanlandsman** [comment] 2017-03-28 17:42
@chcoust @urvashis 

Charles, apologies for not replying earlier - the work on supporting rollup is ongoing, but given its immaturity I'm afraid we can't offer a timeline on us supporting it. It's a great idea but we've found difficult to work with and configure for non-trivial applications.

For the the release after next (ie, after the next release) I'll be making changes to the way we do our exports  which will remove the problems around clientExports, but there are other problems when using rollup that arent trivial to resolve

@urvashis There is documentation on using ag-Grid with webpack, webpack 2 and webpack & ngtools - all of which can be found here: https://www.ag-grid.com/best-angular-2-data-grid/?framework=angular

**Comment by chcoust** [comment] 2017-03-28 19:27
@seanlandsman Thanks for your reply, 

As I was saying in my "edit", we dropped what we tried with rollup and went on with webpack

And all is working for the best :)

**Comment by ralberts** [comment] 2017-06-29 19:56
We also would like to use rollup :-(

**Comment by mortac8** [comment] 2017-10-05 16:40
We would also like to use rollup.  Any updates on this front?  Thanks!

**Comment by ghaiat** [comment] 2018-02-09 11:36
hello
Any update on beeing able to use rollup with ag-grid ?

**Comment by andrea-spotsoftware** [comment] 2018-02-13 17:18
I'm in the same problem.. Big issue with rollup

**Comment by anandmurali** [comment] 2018-05-19 18:35
I was able to resolve the issue by modifying rollup config file as show below.

`    plugins: [
        nodeResolve({ jsnext: true, module: true }),
        commonjs({
            include: ['node_modules/**/*', 
                        'node_modules/primeng/**',
                        **'node_modules/ag-grid-angular/**'**],
            namedExports: {
                'node_modules/primeng/primeng.js': ['ChartModule'],
                **'node_modules/ag-grid-angular/main.js': ['AgGridModule']**
            }
        }),
        uglify()
    ]`

**Comment by jakewhelan** [comment] 2018-09-04 10:35
This issue still exists, unable to bundle ag-grid with rollup

**Comment by Toxicable** [comment] 2019-06-13 06:01
Using 
```
    "ag-grid-angular": "~20.0.0",
    "ag-grid-community": "~20.0.0",
    "ag-grid-enterprise": "~20.0.0",
```
we're getting: 
>Uncaught TypeError: Cannot read property 'GridOptionsWrapper' of undefined

after building our apps with rollup

**Comment by Toxicable** [comment] 2019-06-13 20:38
After doing a bit of investigation, looks like the use of decorators here: https://github.com/ag-grid/ag-grid/blob/3d14f9cc21fd8e9cda791ba0949568925160d64b/packages/ag-grid-community/src/ts/logger.ts#L10 
Is the cause of my error.

Since it results in code like this
```
o([r(0, i.Qualifier("gridOptionsWrapper")), n("design:type", Function), n("design:paramtypes", [gA.GridOptionsWrapper]), n("design:returntype", void 0)], e.prototype, "setBeans", null),
```
where `gA` is not defined

**Comment by publicvirtualvoid** [comment] 2019-06-13 20:48
We rely on rollup and ag-grid (enterprise). Could this please be prioritised?

**Comment by pscarey** [comment] 2019-06-23 05:13
@Toxicable @publicvirtualvoid 

We have the same issue. The code rollup operates on is actually the compiled JS, created from the source you linked. This can be found [here](https://github.com/ag-grid/ag-grid/blob/3d14f9cc21fd8e9cda791ba0949568925160d64b/packages/ag-grid-community/dist/lib/logger.js#L36-L41).

Running the rollup bundle in debug mode gives us:
```
__decorate([__param(0, context_2.Qualifier("gridOptionsWrapper")), __metadata("design:type", Function), __metadata("design:paramtypes", [gridOptionsWrapper.GridOptionsWrapper]), __metadata("design:returntype", void 0)], LoggerFactory.prototype, "setBeans", null);
```
Which is the less-shortened equivalent of what you've posted. The error
> Uncaught TypeError: Cannot read property 'GridOptionsWrapper' of undefined

Seems to then come from `[gridOptionsWrapper.GridOptionsWrapper]` as `gridOptionsWrapper` is not defined. We can actually verify that the `gridOptionsWrapper` is picked up and bundled by rollup by  searching for bundle for the module definition, `var gridOptionsWrapper = `, which means the problem is a little more subtle.

AFAIK, rollup will:
- Instantiate all the modules into the bundle scope as variables so they are available to all modules which depend on them, without `require`.
- Start the bundle at it's entry point.
- Code that was originally a `require` will have been transformed to a using the bundle scoped variable instead.

The `gridOptionsWrapper` bundle scoped variable isn't instantiated yet when the `_decorate` function runs (that is [here again](https://github.com/ag-grid/ag-grid/blob/3d14f9cc21fd8e9cda791ba0949568925160d64b/packages/ag-grid-community/dist/lib/logger.js#L36-L41)). As to why exactly, I'm not sure. It could be `rollup-plugin-commonjs` handling circular deps badly, or an issue parsing the syntax used, or it might be fixable in `ag-grid`. 

One dirty but quick fix is to use `rollup-plugin-replace` (before `rollup-plugin-commonjs`) to stop the decorator throwing:
```
replace({ // ag-grid-community see https://github.com/ag-grid/ag-grid-angular/issues/112
    'gridOptionsWrapper_1.GridOptionsWrapper': 'null',
    delimiters: ['', '']
})
```
Nulling out the `gridOptionsWrapper_1` reference will likely break some functionality, but that might not be important to you. I've used a generic replace, as this also happens in other locations, such as the `eventService` module [here](https://github.com/ag-grid/ag-grid/blob/3d14f9cc21fd8e9cda791ba0949568925160d64b/packages/ag-grid-community/dist/lib/eventService.js#L180-L189).

Note that the ```include: `${nodeModulesRoot}/ag-grid-community/**`,``` option can also be used to restrict the files operated on.

**Comment by Toxicable** [comment] 2019-06-23 05:54
@pscarey Thanks for the investigation.
I think it is likely a circular dep issue, but likely not rollups faultt.
if you take a look at 
`logger` depends on `gridOptionsWrapper`
https://github.com/ag-grid/ag-grid/blob/3d14f9cc21fd8e9cda791ba0949568925160d64b/packages/ag-grid-community/dist/lib/logger.js#L21

`gridOptionsWrapper` depends on `eventService`
https://github.com/ag-grid/ag-grid/blob/3d14f9cc21fd8e9cda791ba0949568925160d64b/packages/ag-grid-community/dist/lib/gridOptionsWrapper.js#L21

`eventService` depends on `logger`
https://github.com/ag-grid/ag-grid/blob/3d14f9cc21fd8e9cda791ba0949568925160d64b/packages/ag-grid-community/dist/lib/eventService.js#L21

You can see it was noticed 2 years ago in this issue: https://github.com/ag-grid/ag-grid/issues/1870
However, nothing appears to have been done to solve it.

Since there is a circular dep there, rollup dosen't know how to give a value to `var gridOptionsWrapper_1 = require("./gridOptionsWrapper");` therefore it gives it `undefined`

**Comment by jonmeyerny** [comment] 2019-09-28 05:11
I also use AgGridEnterprise and am moving to Rollup for internal library packaging, and have been hit by this issue. 

This [article](https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de) describes one coding pattern that could be used to permanently solve circular loading issues on different build systems, by using an extra file in order to pin down loading order. Its a little ugly, but it might be worth investigating. I suspect it would only need to be done for a small collection of the internal dependencies...

**Comment by seanlandsman** [comment] 2019-11-20 18:05
Please refer to the following link: https://www.ag-grid.com/ag-grid-building-rollup/

Does this help?

**Closed** 2019-12-03 16:36 UTC
Labels: enhancement, help wanted
